#!/bin/bash
# Define Neovim applications you want to experiment with.

# The repository cloned must bootstrap itself.  In otherwords, clone and nvim
# is all tha tis needed.
#
# alias      | Github repository       | default or branch name
readonly neovim_distros=(
  "kickstart  | nvim-lua/kickstart.nvim | default"
  "launch     | LunarVim/Launch.nvim    | default"
  "LazyVim    | LazyVim/starter         | default"
  "NormalNvim | NormalNvim/NormalNvim   | default"
)
